### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by fimdomeio** [gliese-technology/picnic#1]
Followed the instructions as stated.
on my scss don't know exactly what the @import statment should be as

> @import "src/plugins.scss"
> gives
> /test.scss: Scss compiler error: File to import: {}/src/plugins not found in file...

**Comment by ramijarrar** [comment]
The syntax for the fourseven:scss package has changed. You should be able to do this something like this "{gliese:picnic}/src/plugins.scss"

**Comment by ramijarrar** [comment]
Please note that we are not actively maintaining (or using) this package anymore, so you'll want to fork the repo to stay up to date with the latest version of the library.
